#pragma once

// SharedMath::Functions — umbrella header
// Usage: #include <functions/functions.h>

#include "SpecialFunctions.h"   // Γ, ψ, β, Bessel, Legendre, elliptic, …
#include "Activations.h"        // sigmoid, relu, gelu, swish, softmax, …
#include "LossFunctions.h"      // mse, cross-entropy, huber, focal, …
