
#ifndef SHAREDMATH_FUNCTIONS_EXPORT_H
#define SHAREDMATH_FUNCTIONS_EXPORT_H

#ifdef SHAREDMATH_FUNCTIONS_STATIC_DEFINE
#  define SHAREDMATH_FUNCTIONS_EXPORT
#  define SHAREDMATH_FUNCTIONS_NO_EXPORT
#else
#  ifndef SHAREDMATH_FUNCTIONS_EXPORT
#    ifdef SharedMath_Functions_EXPORTS
        /* We are building this library */
#      define SHAREDMATH_FUNCTIONS_EXPORT 
#    else
        /* We are using this library */
#      define SHAREDMATH_FUNCTIONS_EXPORT 
#    endif
#  endif

#  ifndef SHAREDMATH_FUNCTIONS_NO_EXPORT
#    define SHAREDMATH_FUNCTIONS_NO_EXPORT 
#  endif
#endif

#ifndef SHAREDMATH_FUNCTIONS_DEPRECATED
#  define SHAREDMATH_FUNCTIONS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SHAREDMATH_FUNCTIONS_DEPRECATED_EXPORT
#  define SHAREDMATH_FUNCTIONS_DEPRECATED_EXPORT SHAREDMATH_FUNCTIONS_EXPORT SHAREDMATH_FUNCTIONS_DEPRECATED
#endif

#ifndef SHAREDMATH_FUNCTIONS_DEPRECATED_NO_EXPORT
#  define SHAREDMATH_FUNCTIONS_DEPRECATED_NO_EXPORT SHAREDMATH_FUNCTIONS_NO_EXPORT SHAREDMATH_FUNCTIONS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SHAREDMATH_FUNCTIONS_NO_DEPRECATED
#    define SHAREDMATH_FUNCTIONS_NO_DEPRECATED
#  endif
#endif

#endif /* SHAREDMATH_FUNCTIONS_EXPORT_H */
