
#ifndef SHAREDMATH_GEOMETRY_EXPORT_H
#define SHAREDMATH_GEOMETRY_EXPORT_H

#ifdef SHAREDMATH_GEOMETRY_STATIC_DEFINE
#  define SHAREDMATH_GEOMETRY_EXPORT
#  define SHAREDMATH_GEOMETRY_NO_EXPORT
#else
#  ifndef SHAREDMATH_GEOMETRY_EXPORT
#    ifdef SharedMath_Geometry_EXPORTS
        /* We are building this library */
#      define SHAREDMATH_GEOMETRY_EXPORT 
#    else
        /* We are using this library */
#      define SHAREDMATH_GEOMETRY_EXPORT 
#    endif
#  endif

#  ifndef SHAREDMATH_GEOMETRY_NO_EXPORT
#    define SHAREDMATH_GEOMETRY_NO_EXPORT 
#  endif
#endif

#ifndef SHAREDMATH_GEOMETRY_DEPRECATED
#  define SHAREDMATH_GEOMETRY_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SHAREDMATH_GEOMETRY_DEPRECATED_EXPORT
#  define SHAREDMATH_GEOMETRY_DEPRECATED_EXPORT SHAREDMATH_GEOMETRY_EXPORT SHAREDMATH_GEOMETRY_DEPRECATED
#endif

#ifndef SHAREDMATH_GEOMETRY_DEPRECATED_NO_EXPORT
#  define SHAREDMATH_GEOMETRY_DEPRECATED_NO_EXPORT SHAREDMATH_GEOMETRY_NO_EXPORT SHAREDMATH_GEOMETRY_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SHAREDMATH_GEOMETRY_NO_DEPRECATED
#    define SHAREDMATH_GEOMETRY_NO_DEPRECATED
#  endif
#endif

#endif /* SHAREDMATH_GEOMETRY_EXPORT_H */
