
#ifndef SHAREDMATH_NUMERICALMETHODS_EXPORT_H
#define SHAREDMATH_NUMERICALMETHODS_EXPORT_H

#ifdef SHAREDMATH_NUMERICALMETHODS_STATIC_DEFINE
#  define SHAREDMATH_NUMERICALMETHODS_EXPORT
#  define SHAREDMATH_NUMERICALMETHODS_NO_EXPORT
#else
#  ifndef SHAREDMATH_NUMERICALMETHODS_EXPORT
#    ifdef SharedMath_NumericalMethods_EXPORTS
        /* We are building this library */
#      define SHAREDMATH_NUMERICALMETHODS_EXPORT 
#    else
        /* We are using this library */
#      define SHAREDMATH_NUMERICALMETHODS_EXPORT 
#    endif
#  endif

#  ifndef SHAREDMATH_NUMERICALMETHODS_NO_EXPORT
#    define SHAREDMATH_NUMERICALMETHODS_NO_EXPORT 
#  endif
#endif

#ifndef SHAREDMATH_NUMERICALMETHODS_DEPRECATED
#  define SHAREDMATH_NUMERICALMETHODS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SHAREDMATH_NUMERICALMETHODS_DEPRECATED_EXPORT
#  define SHAREDMATH_NUMERICALMETHODS_DEPRECATED_EXPORT SHAREDMATH_NUMERICALMETHODS_EXPORT SHAREDMATH_NUMERICALMETHODS_DEPRECATED
#endif

#ifndef SHAREDMATH_NUMERICALMETHODS_DEPRECATED_NO_EXPORT
#  define SHAREDMATH_NUMERICALMETHODS_DEPRECATED_NO_EXPORT SHAREDMATH_NUMERICALMETHODS_NO_EXPORT SHAREDMATH_NUMERICALMETHODS_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SHAREDMATH_NUMERICALMETHODS_NO_DEPRECATED
#    define SHAREDMATH_NUMERICALMETHODS_NO_DEPRECATED
#  endif
#endif

#endif /* SHAREDMATH_NUMERICALMETHODS_EXPORT_H */
