
#ifndef SHAREDMATH_LINEARALGEBRA_EXPORT_H
#define SHAREDMATH_LINEARALGEBRA_EXPORT_H

#ifdef SHAREDMATH_LINEARALGEBRA_STATIC_DEFINE
#  define SHAREDMATH_LINEARALGEBRA_EXPORT
#  define SHAREDMATH_LINEARALGEBRA_NO_EXPORT
#else
#  ifndef SHAREDMATH_LINEARALGEBRA_EXPORT
#    ifdef SharedMath_LinearAlgebra_EXPORTS
        /* We are building this library */
#      define SHAREDMATH_LINEARALGEBRA_EXPORT 
#    else
        /* We are using this library */
#      define SHAREDMATH_LINEARALGEBRA_EXPORT 
#    endif
#  endif

#  ifndef SHAREDMATH_LINEARALGEBRA_NO_EXPORT
#    define SHAREDMATH_LINEARALGEBRA_NO_EXPORT 
#  endif
#endif

#ifndef SHAREDMATH_LINEARALGEBRA_DEPRECATED
#  define SHAREDMATH_LINEARALGEBRA_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SHAREDMATH_LINEARALGEBRA_DEPRECATED_EXPORT
#  define SHAREDMATH_LINEARALGEBRA_DEPRECATED_EXPORT SHAREDMATH_LINEARALGEBRA_EXPORT SHAREDMATH_LINEARALGEBRA_DEPRECATED
#endif

#ifndef SHAREDMATH_LINEARALGEBRA_DEPRECATED_NO_EXPORT
#  define SHAREDMATH_LINEARALGEBRA_DEPRECATED_NO_EXPORT SHAREDMATH_LINEARALGEBRA_NO_EXPORT SHAREDMATH_LINEARALGEBRA_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SHAREDMATH_LINEARALGEBRA_NO_DEPRECATED
#    define SHAREDMATH_LINEARALGEBRA_NO_DEPRECATED
#  endif
#endif

#endif /* SHAREDMATH_LINEARALGEBRA_EXPORT_H */
